### ISSUE TITLE
Is there an easy way to add an ability to run all specs?

### ISSUE THREAD

**Issue by aaronmcadam** [gabebw/vim-spec-runner#25]
One feature I'm missing from `vim-rspec` is being able to run all specs if I choose. Is it difficult to add that, or is there another command I should just use instead? Thanks!

**Comment by christoomey** [comment]
`vim-rspec` doesn't have a builtin mechanism for this as we consider it outside the scope of the plugin (@gabebw, correct me if I'm wrong here). The focus of the plugin is to optimize running from the given file context.

That said, you can easily build your own using tmux runner with:

``` vim
command! RunAllSpecs VtrSendCommandToRunner! rspec spec
nnoremap <leader>R :RunAllSpecs<cr>
```

**Comment by aaronmcadam** [comment]
that's awesome, thanks again @christoomey, that's exactly what I wanted!
