### ISSUE TITLE
Disabling spring or zeus

### ISSUE THREAD

**Issue by cored** [gabebw/vim-spec-runner#28]
I would like to know how to disable any preloader manually; vim-spec-runner is detecting spring in my Gemfile.lock but I can't remove it from it at this point. Is there a way for me to stop using those preloaders?

Thanks.

**Comment by gabebw** [comment]
Hi! Vim-spec-runner will always use a detected preloader if it's available. Maybe you can remove `spring-commands-rspec` from the Gemfile? That's the gem that vim-spec-runner looks for.

**Comment by cored** [comment]
That's the thing I can't remove that from the Gemfile

On 26 April 2015 at 20:44, Gabe Berke-Williams <notifications@github.com>
wrote:

> Hi! Vim-spec-runner will always use a detected preloader if it's
> available. Maybe you can remove spring-commands-rspec from the Gemfile?
> That's the gem that vim-spec-runner looks for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabebw/vim-spec-runner/issues/28#issuecomment-96452584>
> .
>



-- 
Rafael George

**Comment by mcmire** [comment]
If you're using `dotenv-rails`, you can add `DISABLE_SPRING=1` to your `.env` file.

**Comment by cored** [comment]
Not using dotenv-rails; I was actually thinking in adding an option to the
plugin to disable the preloaders.

On 14 May 2015 at 12:53, Elliot Winkler <notifications@github.com> wrote:

> If you're using dotenv-rails, you can add DISABLE_SPRING=1 to your .env
> file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gabebw/vim-spec-runner/issues/28#issuecomment-102101368>
> .
>



-- 
Rafael George

**Comment by mcmire** [comment]
Sorry, I updated the comment to indicate that you can use an environment variable instead. That will disable Spring across the board, but that may or may not be a problem depending on how you use Spring.

**Comment by gabebw** [comment]
Now that #35 is merged, if you pull from master this should disable the preloaders:

``` vim
let g:spec_runner_preloader = ''
```
