### ISSUE TITLE
Doesn't play well with vim-go plugin

### ISSUE THREAD

**Issue by cored** [gabebw/vim-spec-runner#34]
Installing vim-go make some sort of keybindings clash even when my mappings are not the same as the one in vim-go. 

```
au FileType ruby nmap <Leader>rs <Plug>RunCurrentSpecFile
```

Every time I issue `leader + r` I get the following error: 

```
vim-spec-runner: No previous spec command
```

Why the run spec map is still mapped to the old one if I changed it?

**Comment by cored** [comment]
@gabebw I will close this I found my issue; I just needed to also do a map for the re run command.

**Comment by gabebw** [comment]
:+1:
